apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpathpersistent
  resources:
    requests:
      storage: 8Gi
  volumeName: jenkins-pv 