registry: 418295696814.dkr.ecr.ap-southeast-1.amazonaws.com
stage: 'dev'

repoOwner: 'toward-the-stars'
repoName: 'stars-core'
imageTag: '1.0.0'
domain: 'towardthestars.live'
portName: 'http'
ingressOrder: '200'

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Schedule:
nodeSelector: {}
tolerations: []
affinity: {}

webproxy:

  envoyConfigMap: stars-webproxy
  nlb:
    name: nonprod-nlb
    cert: arn:aws:acm:ap-southeast-1:418295696814:certificate/1749ca08-1bab-41c3-8d6f-65b543e8d981

  podAnnotations: {}

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 10Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Schedule:
  nodeSelector: {}
  tolerations: []
  affinity: {}


cmsapi:

  env:
    # Log 等級
    LOG_LEVEL: trace

  podAnnotations: {}

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Schedule:
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontapi:

  env:
    # Log 等級
    LOG_LEVEL: trace

  podAnnotations: {}

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Schedule:
  nodeSelector: {}
  tolerations: []
  affinity: {}

tellerapi:

  env:
    # Log 等級
    LOG_LEVEL: trace

  podAnnotations: {}

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Schedule:
  nodeSelector: {}
  tolerations: []
  affinity: {}