apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpathpersistent
  resources:
    requests:
      storage: 50Gi
  volumeName: harbor-registry-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-database
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpathpersistent
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-database-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-redis
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpathpersistent
  resources:
    requests:
      storage: 1Gi
  volumeName: harbor-redis-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-trivy
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpathpersistent
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-trivy-pv 