apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor-route
  namespace: devops
spec:
  parentRefs:
  - name: gw
    namespace: gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /harbor
    backendRefs:
    - name: harbor-core
      port: 80 