registry: 418295696814.dkr.ecr.ap-southeast-1.amazonaws.com
environment: 'nonprod'

repoOwner: 'kwlai0927'
repository: 'llm-embedding'
imageTag: '1.0.0'
domain: 'towardthestars.live'

podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Schedule:
nodeSelector: {}
tolerations: []
affinity: {}

configFile:
  secret: "llm-embedding"  # 設定要使用的 secret 名稱

healthCheck:
  type: "http"  # 可選: http, tcp, grpc
  http:
    port: 80
    path: "/healthz"
  initialDelaySeconds: 60  # 添加初始延遲，等待模型加載
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1