apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: github.com
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::418295696814:role/nonprod-aws-load-balancer-controller
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/aws-load-balancer-controller
