apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  namespace: gateway
  name: gw
spec:
  gatewayClassName: envoy
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: gw
  listeners:
    - name: http
      protocol: HTTP
      port: 443
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  namespace: gateway
  name: gw
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          # Traffic Routing
          service.beta.kubernetes.io/aws-load-balancer-name: 'nonprod-nlb'
          service.beta.kubernetes.io/aws-load-balancer-type: 'external'
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: 'ip'
          service.beta.kubernetes.io/aws-load-balancer-alpn-policy: 'HTTP2Preferred'

          # Traffic Listening
          service.beta.kubernetes.io/aws-load-balancer-ip-address-type: 'ipv4'

          # TLS
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:418295696814:certificate/1749ca08-1bab-41c3-8d6f-65b543e8d981,arn:aws:acm:ap-southeast-1:418295696814:certificate/4d90f142-f549-42a3-9818-f374e553bb93,arn:aws:acm:ap-southeast-1:418295696814:certificate/6391b92b-bb8d-49db-9b16-c2af452698c9,arn:aws:acm:ap-southeast-1:418295696814:certificate/dbc38b32-c72d-4859-b1a9-dd2b38be06f1
          service.beta.kubernetes.io/aws-load-balancer-scheme: 'internet-facing'