apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srv.name" . }}
  labels:
    {{- include "srv.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "srv.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.srv.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "srv.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.srv.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: srv
          image: "{{ .Chart.Annotations.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- with .Values.srv.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.srv.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.srv.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /app/config/config.yaml
              name: config
              subPath: config.yaml

      volumes:
        - name: config
          secret:
            secretName: {{ .Values.srv.configFile.secretName }}
            optional: true

      {{- with .Values.srv.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.srv.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.srv.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "srv.name" . }}
  labels:
    {{- include "srv.selectorLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "srv.name" . }}
  minReplicas: {{ .Values.srv.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.srv.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.srv.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.srv.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.srv.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.srv.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "srv.name" . }}
  labels:
    {{- include "srv.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
      {{- include "srv.selectorLabels" . | nindent 4 }}

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "srv.name" . }}
spec:
  parentRefs:
    - name: gw
      namesrvce: gateway
  hostnames:
    - {{ .Values.hostname }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "srv.name" . }}
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
