global:
  postgresql:
    auth:
      postgresPassword: "p1ZG2IY4rUkTHtw5"
      username: "kwlai0927"
      password: "M5LcSk5OVNd3QER3"
      database: "kwlai0927"

primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-pvc"
    size: 10Gi
    
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 50m

  service:
    type: NodePort
    ports:
      postgresql: 5432
    nodePorts:
      postgresql: 31474

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

metrics:
  enabled: false 