apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.repoName }}
  labels:
    {{- include "spa.labels" . | nindent 4 }}
    {{- include "spa.selectorLabels" . | nindent 4 }}
data:
  mime.types: |-
    {{ .Files.Get "nginx/mime.types" | nindent 4 }}

  nginx.conf: |-
    {{ .Files.Get "nginx/nginx.conf" | nindent 4 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.repoName }}
  labels:
    {{- include "spa.labels" . | nindent 4 }}
    {{- include "spa.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spa.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spa.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spa
          image: "{{ .Values.registry }}/{{ .Values.repoOwner }}/{{ .Values.repoName }}:{{ .Values.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: nginx
          configMap:
            name: {{ .Values.repoName }}
            optional: true

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.repoName }}
  labels:
    {{- include "spa.labels" . | nindent 4 }}
    {{- include "spa.selectorLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.repoName }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.repoName }}
  labels:
    {{- include "spa.labels" . | nindent 4 }}
    {{- include "spa.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
      {{- include "spa.selectorLabels" . | nindent 4 }}

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.repoName }}
spec:
  parentRefs:
    - name: gw
      namespace: gateway
  hostnames:
    - {{ printf "%s.%s.%s" .Values.repoName .Values.stage .Values.domain }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.repoName }}
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
