registry: 
version:

hostname: things-thingsapi.dev.towardthestars.live
thingsapi:
  podAnnotations: {}
  imagePullSecrets: []
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
  livenessProbe:
    httpGet:
      path: "/health"
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    httpGet:
      path: "/health"
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  configFile:
    secretName: "things-srv"  # 設定要使用的 secret 名稱
