name: Deploy ECR Image to EKS

on:
  repository_dispatch:
    types:
    - custom-chart

  workflow_dispatch:
    inputs:
      repository:
        required: true
        type: string
      chart-tag:
        required: true
        type: string
      environment:
        required: true
        type: string
      namespace:
        required: true
        type: string

permissions:
  id-token: write # This is required for aws-actions/configure-aws-credentials@v4
  contents: write  # This is required for actions/checkout

jobs:
  
  deploy:
    name: Deploy Helm to Kubernetes
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
    - name: Show Client_Payload
      id: params
      run: |
        REPOSITORY=${{ inputs.repository && inputs.repository ||  github.event.client_payload.repository }}
        IMAGE_TAG=${{ inputs.image-tag && inputs.image-tag || github.event.client_payload.image-tag }}
        ENVIRONMENT=${{ inputs.environment && inputs.environment || github.event.client_payload.environment }}
        NAMESPACE=${{ inputs.namespace && inputs.namespace || github.event.client_payload.namespace }}
        REGISTRY=418295696814.dkr.ecr.ap-southeast-1.amazonaws.com
        if [[ "$REPOSITORY" == *"/"* ]]; then
          IFS='/' read -r REPO_OWNER REPOSITORY <<< $REPOSITORY
          REGISTRY=$REGISTRY/$REPO_OWNER
        else
          REPO_OWNER=""
        fi
        echo "repo-owner=$REPO_OWNER" >> $GITHUB_OUTPUT
        echo "repository=$REPOSITORY" >> $GITHUB_OUTPUT
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT

    - name: 01. Checkout
      uses: actions/checkout@v4

    - name: 02. Configure AWS credentials
      id: credential
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_NONPROD_DEPLOY_ROLE_ARN }}
        aws-region: ap-southeast-1

    - name: 03. install Helm CLI
      uses: azure/setup-helm@v4.2.0
      id: install

    - name: 04. Helm Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region ap-southeast-1 | helm registry login --username AWS --password-stdin 418295696814.dkr.ecr.ap-southeast-1.amazonaws.com

    - name: 05. Install kubectl
      uses: azure/setup-kubectl@v4.0.0

    - name: 06. Update kubeconfig
      run: aws eks update-kubeconfig --name nonprod-eks

    - name: 07. Deploy helm chart to EKS
      working-directory: ${{ steps.params.outputs.environment }}/${{ steps.params.outputs.repository }}
      run: |
        helm upgrade -i -f values.yaml -n ${{ steps.params.outputs.namespace }} \
        --set registry=${{ steps.params.outputs.registry }} \
        --set repository=${{ steps.params.outputs.repository }} \
        --set chart-tag=${{ steps.params.outputs.chart-tag }} \
        ${{ steps.params.outputs.repository }} oci://${{ steps.params.outputs.registry }}/${{ github.event.repository }}
